name: Azure ACR Workflow

on:
  push:
    branches:
      - deployment

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Azure login using User-assigned Managed Identity
      - name: Azure login
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build \
            --build-arg PORT=${{ secrets.PORT }} \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --build-arg JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }} \
            --build-arg JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }} \
            --build-arg JWT_REFRESH_EXPIRES_IN=${{ secrets.JWT_REFRESH_EXPIRES_IN }} \
            --build-arg API_GATEWAY_URL=${{ secrets.API_GATEWAY_URL }} \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/user-service:latest .

      # Push the Docker image to Azure Container Registry
      - name: Push Docker image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/user-service:latest